Repository TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage, pull requests merged in 2024-10, with the labels that each got.

#171 [TASK] Use --minimal-test CLI option for documentation tests
  .github/workflows/documentation.yml
  Makefile
Labels: backport 11.5, backport 12.4

#191 [TASK] Delete Preface
  Documentation/Index.rst
  Documentation/Preface/Index.rst
Labels: backport 11.5, backport 12.4

#190 [TASK] Introduce cards
  Documentation/Index.rst
Labels: backport 12.4

#189 [FEATURE] Create a minimal site package
  Documentation/Index.rst
  Documentation/MinimalExample/AddSiteSet.png
  Documentation/MinimalExample/Index.rst
  Documentation/MinimalExample/_config.yaml
  Documentation/MinimalExample/_config.yaml.diff
  Documentation/MinimalExample/_minimal.typoscript
  Documentation/MinimalExample/_pageview.typoscript
Labels: backport-required

#196 [TASK] Improve the Fluid section
  Documentation/FluidTemplates/Index.rst
  Documentation/FluidTemplates/MoreInformation/Index.rst
  Documentation/Index.rst
Labels: backport-required

#195 [TASK] Write a basic introduction page
  Documentation/Introduction/Index.rst
Labels: backport 12.4

#205 [TASK] Unify Site Package Tutorial title
  Documentation/guides.xml
Labels: backport 12.4, backport 13.4

#210 [TASK] Update information on content rendering
  Documentation/CodeSnippets/ExtensionConfiguration/ComposerJson.rst.txt
  Documentation/CodeSnippets/Fluid/PartialContent.rst.txt
  Documentation/CodeSnippets/PageLayout/Default.rst.txt
  Documentation/CodeSnippets/PageLayout/page.rst.txt
  Documentation/CodeSnippets/codesnippets.php
  Documentation/ContentMapping/AddContent.rst
  Documentation/ContentMapping/Index.rst
  Documentation/ContentMapping/Jumbotron.rst
  Documentation/ContentMapping/SubpageLayout.rst
  Documentation/ContentMapping/_codesnippets/_SectionMain.html
  Documentation/ContentMapping/_codesnippets/_SectionMainDebug.diff
  Documentation/ContentMapping/_codesnippets/_SectionMainRender.diff
  Documentation/ContentMapping/_codesnippets/_SectionMainRenderPartial.diff
  Documentation/ContentMapping/_codesnippets/_pageview.diff
  Documentation/ContentMapping/_images/contents_debug.png
  Documentation/FluidTemplates/_codesnippets/_SectionMain.html
  Documentation/Index.rst
  Documentation/MinimalExample/Index.rst
Labels: backport 13.4
